site_name: StarryNight
site_description: StarryNight - toolkit for optical pooled screening
repo_url: https://github.com/broadinstitute/starrynight
edit_uri: blob/main/docs/

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  # logo: logo.svg
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - content.code.copy

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Core Concepts: user/core-concepts.md
    - Parser Configuration: user/parser-configuration.md
    - Processing Modules: user/modules.md
    - Example CLI Pipeline: user/example-pipeline-cli.md
  - Algorithms:
    - Overview: user/algorithms/README.md
    - Documentation Guide: user/algorithms/DOCUMENTATION_GUIDE.md
    - Illumination Calculation: user/algorithms/illum_calc.md
    - Illumination Apply: user/algorithms/illum_apply.md
    - Pre-segmentation Check: user/algorithms/presegcheck.md
    - Segmentation Check: user/algorithms/segcheck.md
    - Alignment: user/algorithms/align.md
    - Preprocessing: user/algorithms/preprocess.md
    - Stitch and Crop: user/algorithms/stitchcrop.md
    - Analysis: user/algorithms/analysis.md
  - Development:
    - Developer Guide: developer/developer-guide.md
    - PCPIP Specs: developer/pcpip-specs.md
    - Pipeline Automation: developer/pipeline-automation.md
    - Requirements: developer/requirements.md
  - Architecture:
    - Overview: architecture/00_architecture_overview.md
    - Algorithm Foundation: architecture/01_algorithms_foundation.md
    - CLI Integration: architecture/03_cli_integration.md
    - Module Abstraction: architecture/04_module_abstraction.md
    - Bilayer Integration: architecture/05_bilayer_integration.md
    - Pipecraft Integration: architecture/06_pipecraft_integration.md
    - Execution Model: architecture/07_execution_model.md
    - Snakemake Backend: architecture/08_snakemake_backend.md
    - Experiment Configuration: architecture/09_experiment_configuration.md
    - Module Configuration: architecture/10_11_module_configuration.md
    - Pipeline Composition: architecture/12_pipeline_composition_execution.md
    - Architecture for Biologists: architecture/13_architecture_for_biologists.md
    - Documentation Guide: architecture/_documentation_guide.md
  - Testing: tester/README.md
  - FAQ: misc/faq.md

plugins:
  - search
  - mermaid2:
    # arguments:
    #     # test if its __palette_0/1 (dark) or __palette_1/2 (light)
    #   theme: |
    #     ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  # - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  # - pymdownx.superfences:
  #     custom_fences:
  #       - name: mermaid
  #         class: mermaid
  #         format: !!python/name:pymdownx.superfences.fence_code_format
