site_name: StarryNight
site_description: StarryNight - toolkit for optical pooled screening
repo_url: https://github.com/broadinstitute/starrynight
edit_uri: blob/main/docs/

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  # logo: logo.svg
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking
  - content.code.copy

nav:
  - Home: index.md
  - User Guide:
    - Getting Started: user/getting-started.md
    - Core Concepts: user/core-concepts.md
    - Parser Configuration: user/parser-configuration.md
    - Processing Modules: user/modules.md
    - Example CLI Pipeline: user/example-pipeline-cli.md
  - Algorithms:
    - Overview: user/algorithms/README.md
    - Documentation Guide: user/algorithms/DOCUMENTATION_GUIDE.md
    - Illumination Calculation: user/algorithms/illum_calc.md
    - Illumination Apply: user/algorithms/illum_apply.md
    - Pre-segmentation Check: user/algorithms/presegcheck.md
    - Segmentation Check: user/algorithms/segcheck.md
    - Alignment: user/algorithms/align.md
    - Preprocessing: user/algorithms/preprocess.md
    - Stitch and Crop: user/algorithms/stitchcrop.md
    - Analysis: user/algorithms/analysis.md
  - Development:
    - Developer Guide: developer/developer-guide.md
    - PCPIP Specs: developer/pcpip-specs.md
    - Pipeline Automation: developer/pipeline-automation.md
    - Requirements: developer/requirements.md
  - Architecture:
      - Overview: architecture/00_architecture_overview.md
      - Algorithm Layer: architecture/01_algorithm_layer.md
      - CLI Layer: architecture/02_cli_layer.md
      - Module Layer: architecture/03_module_layer.md
      - Pipeline Layer: architecture/04_pipeline_layer.md
      - Execution Layer: architecture/05_execution_layer.md
      - Configuration Layer: architecture/06_configuration_layer.md
      - Architecture for Biologists: architecture/07_architecture_for_biologists.md
      - Practical Integration: architecture/08_practical_integration.md
  - Testing: tester/README.md

plugins:
  - search
  - mermaid2:
    # arguments:
    #     # test if its __palette_0/1 (dark) or __palette_1/2 (light)
    #   theme: |
    #     ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'

markdown_extensions:
  - attr_list
  - admonition
  - footnotes
  - md_in_html
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
