site_name: StarryNight
site_description: StarryNight - toolkit for optical pooled screening
repo_url: https://github.com/broadinstitute/starrynight
edit_uri: blob/main/docs/

validation:
  omitted_files: warn
  absolute_links: relative_to_docs
  unrecognized_links: warn
  anchors: warn

theme:
  name: material
  # logo: logo.svg
  language: en
  palette:
  - media: '(prefers-color-scheme: light)'
    scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    scheme: slate
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
  features:
  - navigation.expand
  - navigation.indexes
  - navigation.sections
  - navigation.tabs
  - navigation.top
  - navigation.tracking

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Quick Start Guide: getting-started/quickstart.md
  - User Guide:
    - Core Concepts: user/core-concepts.md
    - Parser Configuration: user/parser-configuration.md
    - Processing Modules: user/modules.md
    - Example CLI Pipeline: user/example-pipeline-cli.md
  - Algorithms:
    - Overview: user/algorithms/README.md
    - Documentation Guide: user/algorithms/DOCUMENTATION_GUIDE.md
    - Illumination Calculation: user/algorithms/illum_calc.md
    - Illumination Apply: user/algorithms/illum_apply.md
    - Pre-segmentation Check: user/algorithms/presegcheck.md
    - Segmentation Check: user/algorithms/segcheck.md
    - Alignment: user/algorithms/align.md
    - Preprocessing: user/algorithms/preprocess.md
    - Stitch and Crop: user/algorithms/stitchcrop.md
    - Analysis: user/algorithms/analysis.md
  - Development:
    - Developer Guide: developer/developer-guide.md
    - PCPIP Specs: developer/pcpip-specs.md
    - Requirements: developer/requirements.md
  - Testing:
    - Testing Framework: tester/README.md
    - PCPIP pipelines: tester/assets/pcpip-pipelines/README.md
    - PCPIP fixtures: tester/assets/pcpip-create-fixture/README.md
    - PCPIP tests: tester/assets/pcpip-test/README.md
    - PCPIP dummy fixtures: tester/assets/pcpip-generate-dummy-structures/README.md
  - FAQ: misc/faq.md

plugins:
- mermaid2:
    arguments:
        # test if its __palette_0/1 (dark) or __palette_1/2 (light)
      theme: |
        ^(JSON.parse(__md_get("__palette").index == 1)) ? 'dark' : 'light'
